version: "3"
services:
 master:
  container_name: master_db
  build: ./master
  volumes:
   - data:/var/lib/postgresql/data
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=postgres
   - POSTGRES_MULTIPLE_DATABASES=merchant_bpmn_service_db,merchant_order_service_db,merchant_product_service_db,merchant_service_db,merchant_system_params_service_db,merchant_user_service_db
   - PG_REP_USER=merchant_replicator
   - PG_REP_PASSWORD=FvX63dqZ
  ports:
    - 5432:5432
  networks:
   default:
    aliases:
     - pg_cluster
 slave:
  container_name: slave_db
  build: ./slave
  environment:
   - PG_REP_USER=merchant_replicator
   - PG_REP_PASSWORD=FvX63dqZ
  ports:
    - 5433:5432
  networks:
   default:
    aliases:
     - pg_cluster
volumes:
 data: