version: '3.1'
 
services:
 db:
  container_name: master_merchant_db
  build: .
  volumes:
   - data:/var/lib/postgresql/data
  environment:
   - POSTGRES_MULTIPLE_DATABASES=merchant_bpmn_service_db,merchant_order_service_db,merchant_product_service_db,merchant_service_db,merchant_system_params_service_db,merchant_user_service_db,merchant_report_service_db
   - PG_REP_USER=merchant_replicator
   - PG_REP_PASSWORD=FvX63dqZ
  ports:
    - 5432:5432
volumes:
    data:
