version: '3.1'
 
services:
 pg_master:
  container_name: merchant_db
  build: .
  volumes:
   - ./data:/var/lib/postgresql/data # if windows OS, change to "- pg_data:/var/lib/postgresql/data" then create a volume pg_data
  environment:
   - POSTGRES_USER=merchant_user
   - POSTGRES_PASSWORD=merchantq!213Q1!
   - POSTGRES_DB=merchant_user
   - POSTGRES_MULTIPLE_DATABASES=merchant_bpmn_service_db,merchant_order_service_db,merchant_product_service_db,merchant_service_db,merchant_system_params_service_db,merchant_user_service_db
   - PG_REP_USER=merchant_replicator
   - PG_REP_PASSWORD=FvX63dqZ
  ports:
    - 5432:5432
#volumes:
    #pg_data:
