version: '3.1'
 
services:
 db:
  container_name: slave_merchant_db
  build: .
  volumes:
   - data:/var/lib/postgresql/data
  environment:
   - PG_REP_USER=merchant_replicator
   - PG_REP_PASSWORD=FvX63dqZ
  ports:
    - 5433:5432
volumes:
    data:
